emerline/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('emerline.task.urls')),
    url(r'', include('emerline.project.urls')),
    url(r'', include('emerline.user.urls')),
    url(r'', include('emerline.main.urls'))
]

emerline/user/urls.py
from django.conf.urls import url

from . import views

app_name = 'user'
urlpatterns = [
    url(r'^user/(?P<pk>\d+)$', views.DeveloperReadView.as_view()),
    url(r'^user/(?P<pk>\d+)/delete$', views.DeveloperDeleteView.as_view()),
    url(r'^user/new', views.create_developer),
    url(r'^user/(?P<pk>\d+)/update$', views.DeveloperUpdateView.as_view()),
    url(r'^user/api/$', views.UserList.as_view()),
    url(r'^user/api/new$', views.UserCreate.as_view()),
    url(r'^user/api/(?P<pk>\d+)$', views.UserDetail.as_view()),
]

emerline/project/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class Project(models.Model):
    projectName = models.CharField(max_length=100)
    users = models.ManyToManyField(User)

    class Meta:
        permissions = (
            ('view_project', 'Can view project'),
        )

    def __str__(self):
        return self.projectName

emerline/task/models.py
from django.contrib.auth.models import User
from django.db import models

from emerline.project.models import Project


class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=400)
    dueDate = models.DateTimeField()
    user = models.ForeignKey(User)
    projects = models.ForeignKey(Project, null=True, blank=True)

    class Meta:
        permissions = (
            ('view_task', 'Can view task'),
        )

    def __str__(self):
        return self.title

emerline/user/models.py
from django.db import models

# Create your models here.

emerline/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class DeveloperCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

emerline/user/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import User, Group, Permission
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import UpdateView
from rest_framework import generics

from emerline.main.views import DEVELOPER_PERMISSIONS
from emerline.user.forms import DeveloperCreateForm
from emerline.user.serializers import UserSerializer


@permission_required('auth.add_user')
def create_developer(request):
    if request.method == 'POST':
        form = DeveloperCreateForm(request.POST)
        if form.is_valid():
            developer = User.objects.create_user(username=form.cleaned_data['username'],
                                                 password=form.cleaned_data['password1'],
                                                 email=form.cleaned_data['email'])
            group, created = Group.objects.get_or_create(name='developer')
            if created:
                permissions = [Permission.objects.get(codename=codename) for codename in DEVELOPER_PERMISSIONS]
                group.permissions.add(*permissions)
            developer.groups.add(group)
            developer.save()
            # email = EmailMessage('11', '22', to=['sluchak1995@gmail.com'])
            # email.send()
            return redirect("/")
    else:
        form = DeveloperCreateForm()

    return render(request, 'user/create_developer.html', {'form': form})


class DeveloperReadView(DetailView):
    model = User
    template_name = 'user/user_detail.html'

    def dispatch(self, *args, **kwargs):
        return super(DeveloperReadView, self).dispatch(*args, **kwargs)


class DeveloperUpdateView(UpdateView):
    model = User
    template_name = 'update.html'
    fields = ('username', 'email',)
    success_url = '/'

    @method_decorator(permission_required('auth.change_user'))
    def dispatch(self, *args, **kwargs):
        return super(DeveloperUpdateView, self).dispatch(*args, **kwargs)


class DeveloperDeleteView(DeleteView):
    model = User
    success_url = "/"

    @method_decorator(permission_required('auth.delete_user'))
    def dispatch(self, *args, **kwargs):
        return super(DeveloperDeleteView, self).dispatch(*args, **kwargs)


class UserList(generics.ListCreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserCreate(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

templates/user/create_developer.html
<!DOCTYPE html>
<html>
  <head>
    <title>Create developer</title>
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" value="create_developer">Create</button>
    </form>
  </body>
</html>

templates/user/user_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
    <table>
        <tr>
            <th>Username :</th>
            <td>{{ user }}</td>
        </tr>
        <tr>
            <th>Email:</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Projects:</th>
            {% for project in user.project_set.all %}
                <td>{{ project.projectName }}</td>
            {% endfor %}
        </tr>
        <tr>
            <th>Tasks</th>
            {% for task in user.task_set.all %}
                <td>{{ task.title }}</td>
                <td>{{ task.description }}</td>
                <td>{{ task.dueDate }}</td>
                <td>{{ task.projects }}</td>
            {% endfor %}
        </tr>
    </table>
{% endblock %}
</body>
</html>